# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hjpubuntu22045/korea_c

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hjpubuntu22045/korea_c

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hjpubuntu22045/korea_c/CMakeFiles /home/hjpubuntu22045/korea_c//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hjpubuntu22045/korea_c/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bookSql

# Build rule for target.
bookSql: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bookSql
.PHONY : bookSql

# fast build rule for target.
bookSql/fast:
	$(MAKE) $(MAKESILENT) -f sqlquery/CMakeFiles/bookSql.dir/build.make sqlquery/CMakeFiles/bookSql.dir/build
.PHONY : bookSql/fast

#=============================================================================
# Target rules for targets named 1

# Build rule for target.
1 : cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 1
.PHONY : 1

# fast build rule for target.
1/fast:
	$(MAKE) $(MAKESILENT) -f c_example/day1and2/CMakeFiles/1.dir/build.make c_example/day1and2/CMakeFiles/1.dir/build
.PHONY : 1/fast

#=============================================================================
# Target rules for targets named arithmetics

# Build rule for target.
arithmetics: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 arithmetics
.PHONY : arithmetics

# fast build rule for target.
arithmetics/fast:
	$(MAKE) $(MAKESILENT) -f c_example/day1and2/CMakeFiles/arithmetics.dir/build.make c_example/day1and2/CMakeFiles/arithmetics.dir/build
.PHONY : arithmetics/fast

#=============================================================================
# Target rules for targets named celsius2farh

# Build rule for target.
celsius2farh: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 celsius2farh
.PHONY : celsius2farh

# fast build rule for target.
celsius2farh/fast:
	$(MAKE) $(MAKESILENT) -f c_example/day1and2/CMakeFiles/celsius2farh.dir/build.make c_example/day1and2/CMakeFiles/celsius2farh.dir/build
.PHONY : celsius2farh/fast

#=============================================================================
# Target rules for targets named charNumber

# Build rule for target.
charNumber: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 charNumber
.PHONY : charNumber

# fast build rule for target.
charNumber/fast:
	$(MAKE) $(MAKESILENT) -f c_example/day1and2/CMakeFiles/charNumber.dir/build.make c_example/day1and2/CMakeFiles/charNumber.dir/build
.PHONY : charNumber/fast

#=============================================================================
# Target rules for targets named compare

# Build rule for target.
compare: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 compare
.PHONY : compare

# fast build rule for target.
compare/fast:
	$(MAKE) $(MAKESILENT) -f c_example/day1and2/CMakeFiles/compare.dir/build.make c_example/day1and2/CMakeFiles/compare.dir/build
.PHONY : compare/fast

#=============================================================================
# Target rules for targets named compare2

# Build rule for target.
compare2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 compare2
.PHONY : compare2

# fast build rule for target.
compare2/fast:
	$(MAKE) $(MAKESILENT) -f c_example/day1and2/CMakeFiles/compare2.dir/build.make c_example/day1and2/CMakeFiles/compare2.dir/build
.PHONY : compare2/fast

#=============================================================================
# Target rules for targets named ddd

# Build rule for target.
ddd: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ddd
.PHONY : ddd

# fast build rule for target.
ddd/fast:
	$(MAKE) $(MAKESILENT) -f c_example/day1and2/CMakeFiles/ddd.dir/build.make c_example/day1and2/CMakeFiles/ddd.dir/build
.PHONY : ddd/fast

#=============================================================================
# Target rules for targets named fahr2cel

# Build rule for target.
fahr2cel: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fahr2cel
.PHONY : fahr2cel

# fast build rule for target.
fahr2cel/fast:
	$(MAKE) $(MAKESILENT) -f c_example/day1and2/CMakeFiles/fahr2cel.dir/build.make c_example/day1and2/CMakeFiles/fahr2cel.dir/build
.PHONY : fahr2cel/fast

#=============================================================================
# Target rules for targets named foutBit

# Build rule for target.
foutBit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 foutBit
.PHONY : foutBit

# fast build rule for target.
foutBit/fast:
	$(MAKE) $(MAKESILENT) -f c_example/day1and2/CMakeFiles/foutBit.dir/build.make c_example/day1and2/CMakeFiles/foutBit.dir/build
.PHONY : foutBit/fast

#=============================================================================
# Target rules for targets named genderRatio

# Build rule for target.
genderRatio: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 genderRatio
.PHONY : genderRatio

# fast build rule for target.
genderRatio/fast:
	$(MAKE) $(MAKESILENT) -f c_example/day1and2/CMakeFiles/genderRatio.dir/build.make c_example/day1and2/CMakeFiles/genderRatio.dir/build
.PHONY : genderRatio/fast

#=============================================================================
# Target rules for targets named increment

# Build rule for target.
increment: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 increment
.PHONY : increment

# fast build rule for target.
increment/fast:
	$(MAKE) $(MAKESILENT) -f c_example/day1and2/CMakeFiles/increment.dir/build.make c_example/day1and2/CMakeFiles/increment.dir/build
.PHONY : increment/fast

#=============================================================================
# Target rules for targets named infinit

# Build rule for target.
infinit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 infinit
.PHONY : infinit

# fast build rule for target.
infinit/fast:
	$(MAKE) $(MAKESILENT) -f c_example/day1and2/CMakeFiles/infinit.dir/build.make c_example/day1and2/CMakeFiles/infinit.dir/build
.PHONY : infinit/fast

#=============================================================================
# Target rules for targets named limit

# Build rule for target.
limit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 limit
.PHONY : limit

# fast build rule for target.
limit/fast:
	$(MAKE) $(MAKESILENT) -f c_example/day1and2/CMakeFiles/limit.dir/build.make c_example/day1and2/CMakeFiles/limit.dir/build
.PHONY : limit/fast

#=============================================================================
# Target rules for targets named literal

# Build rule for target.
literal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 literal
.PHONY : literal

# fast build rule for target.
literal/fast:
	$(MAKE) $(MAKESILENT) -f c_example/day1and2/CMakeFiles/literal.dir/build.make c_example/day1and2/CMakeFiles/literal.dir/build
.PHONY : literal/fast

#=============================================================================
# Target rules for targets named oddeven

# Build rule for target.
oddeven: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 oddeven
.PHONY : oddeven

# fast build rule for target.
oddeven/fast:
	$(MAKE) $(MAKESILENT) -f c_example/day1and2/CMakeFiles/oddeven.dir/build.make c_example/day1and2/CMakeFiles/oddeven.dir/build
.PHONY : oddeven/fast

#=============================================================================
# Target rules for targets named sizeof

# Build rule for target.
sizeof: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sizeof
.PHONY : sizeof

# fast build rule for target.
sizeof/fast:
	$(MAKE) $(MAKESILENT) -f c_example/day1and2/CMakeFiles/sizeof.dir/build.make c_example/day1and2/CMakeFiles/sizeof.dir/build
.PHONY : sizeof/fast

#=============================================================================
# Target rules for targets named triangle

# Build rule for target.
triangle: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 triangle
.PHONY : triangle

# fast build rule for target.
triangle/fast:
	$(MAKE) $(MAKESILENT) -f c_example/day1and2/CMakeFiles/triangle.dir/build.make c_example/day1and2/CMakeFiles/triangle.dir/build
.PHONY : triangle/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... 1"
	@echo "... arithmetics"
	@echo "... bookSql"
	@echo "... celsius2farh"
	@echo "... charNumber"
	@echo "... compare"
	@echo "... compare2"
	@echo "... ddd"
	@echo "... fahr2cel"
	@echo "... foutBit"
	@echo "... genderRatio"
	@echo "... increment"
	@echo "... infinit"
	@echo "... limit"
	@echo "... literal"
	@echo "... oddeven"
	@echo "... sizeof"
	@echo "... triangle"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

